Update Animals Table
ahmidou09/Vet-clinic-database pull request #2
Opened 2023-09-20 20:10 UTC by ahmidou09

## Changes Made:
- Added a column `species` of type string to the animals table.
- Inserted data for various animals.
- Implemented transactions for updating and deleting records in the animals table.

## Transactions Summary:
- Transaction 1: Set species column to unspecified and rolled back changes.
- Transaction 2: Updated species for animals with names ending in "mon" to "digimon" and set species for animals without a species already set to "pokemon".
- Transaction 3: Deleted records in the animals table and rolled back the transaction.
- Transaction 4: Deleted animals born after Jan 1st, 2022; updated weights; and rolled back to a savepoint.

## Queries Answered:
- How many animals are there?
- How many animals have never tried to escape?
- What is the average weight of animals?
- Who escapes the most, neutered or not neutered animals?
- What is the minimum and maximum weight of each type of animal?
- What is the average number of escape attempts per animal type of those born between 1990 and 2000?

## Screenshots:

- Update data sql with new insertions
<img width="796" alt="01 Update data sql with new insertions" src="https://github.com/ahmidou09/Vet-clinic-database/assets/122125958/5ac63631-072a-4843-ba0b-01eb07ca9afb">

- Inserted data for various animals
<img width="770" alt="02 Inserted data for various animals" src="https://github.com/ahmidou09/Vet-clinic-database/assets/122125958/d1c0b1e1-f1cb-4fa9-8b89-7352a9240a68">

- Update data sql with new insertions
<img width="645" alt="03 Update data sql with new insertions" src="https://github.com/ahmidou09/Vet-clinic-database/assets/122125958/835cbaab-f3af-4953-9fe1-ee99dacc3183">

- Update the 'species' column to 'unspecified' and then rollback
<img width="635" alt="Update the 'species' column to 'unspecified' and then rollback" src="https://github.com/ahmidou09/Vet-clinic-database/assets/122125958/58338e4e-d485-40cb-8c1a-df418ab8deb5">

- Update 'species' based on conditions and commit changes
<img width="623" alt="05 Update 'species' based on conditions and commit changes" src="https://github.com/ahmidou09/Vet-clinic-database/assets/122125958/06afdb00-54c9-4e07-8552-a2110bab9125">

-  Delete all records and rollback
<img width="625" alt="06 Delete all records and rollback" src="https://github.com/ahmidou09/Vet-clinic-database/assets/122125958/ad849756-dd94-4e1a-9973-a03aec0d6bba">

- Update weights and commit changes
<img width="604" alt="07 Update weights and commit changes" src="https://github.com/ahmidou09/Vet-clinic-database/assets/122125958/a351d135-1b7a-42d4-91fc-bb529baf2051">

- How many animals are there?
<img width="622" alt="08 How many animals are there" src="https://github.com/ahmidou09/Vet-clinic-database/assets/122125958/b8f57b97-88c2-4175-9054-20325723cedd">

- How many animals have never tried to escape?
<img width="650" alt="09   How many animals have never tried to escape" src="https://github.com/ahmidou09/Vet-clinic-database/assets/122125958/304d960b-7b78-4d01-8b15-845e9d2c2050">

- What is the average weight of animals?
<img width="598" alt="10 What is the average weight of animals" src="https://github.com/ahmidou09/Vet-clinic-database/assets/122125958/7e057954-4e38-4492-9be1-247cf376a31a">

- Who escapes the most, neutered or not neutered animals?
<img width="623" alt="11 Who escapes the most, neutered or not neutered animals" src="https://github.com/ahmidou09/Vet-clinic-database/assets/122125958/266db6e9-aa9d-4834-ba94-0c161d0f3c94">

-  What is the minimum and maximum weight of each type of animal?
<img width="655" alt="12 What is the minimum and maximum weight of each type of animal" src="https://github.com/ahmidou09/Vet-clinic-database/assets/122125958/908dbeaf-68b0-487a-af96-a87849525cdf">

-  What is the average number of escape attempts per animal type of those born between 1990 and 2000?
<img width="643" alt="13  What is the average number of escape attempts per animal type of those born between 1990 and 2000" src="https://github.com/ahmidou09/Vet-clinic-database/assets/122125958/789d1ffb-fb10-49e4-991d-98e440e61553">

2023-09-20 21:18 UTC, Strangeal requested changes
Hi @ahmidou09, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGYyYWNkMjRkY2JjYjg1MjY1M2NjYTNkNWNiNTQwN2EyZGZmNWM5YSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/m3864rBwwBTKMAbpn3/giphy.gif)


## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Professional `README` template ✅ 
- Correct `GitHub` workflow ✅ 
- Meaningful **Github** commits ✅ 
- Correct `.github/workflows` for linters ✅ 
- Well-structured project ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-20 21:18 UTC, Strangeal commented on queries.sql
> +ROLLBACK;
- [ ] Great work on your query to update the `species` column in the `animal` table! 👏 However, as a best practice, it's crucial to verify the success of your changes after each transaction. To ensure that the rollback operation effectively undoes the changes, I recommend querying the `animal` table following the rollback. This step adds an extra layer of confidence in the integrity of your database.

  - By executing a simple query to retrieve the data from the `animal` table after the rollback, you can confirm whether the changes were properly rolled back and that the data remains consistent.

Happy coding! 😊🚀🍀

2023-09-20 21:18 UTC, Strangeal commented on queries.sql
> +
- [ ] Great work on your query to delete all records from the animal table! 👏 However, as a best practice, it's crucial to verify the success of your changes after each transaction. To ensure that the rollback operation effectively undoes the changes, I recommend querying the animal table following the rollback. This step adds an extra layer of confidence in the integrity of your database.

   - By executing a simple query to retrieve the data from the animal table after the rollback, you can confirm whether the changes were properly rolled back and that the data remains consistent.
   
Happy coding! 😊🚀🍀

2023-09-21 00:45 UTC, MahmoudBakr23 approved these changes
Hi @ahmidou09 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Highlights**
- Well done working on this milestone so far. It is complete! 💯 

Cheers, and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-21 09:29 UTC, merged